# Generated by Django 5.1.7 on 2025-03-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scampost',
            name='image',
        ),
        migrations.CreateModel(
            name='ScamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scam_images/')),
                ('scam_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_dashboard.scampost')),
            ],
        ),
    ]
