# Generated by Django 5.1.7 on 2025-03-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_remove_scampost_image_scamimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scampost',
            name='stk_scam',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Số tài khoản'),
        ),
    ]
